
#定义外部上传路径
web:
 upload-path: /Users/user12/Desktop/upload/




spring:
  redis:
  database: 1
  host: localhost
  pool:
    max-active: 20
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: 123456
    schema: classpath:db/schema.sql  #进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。
    data: classpath:db/data.sql    #进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb

  jpa:
   hibernate:
     ddl-auto: update
     show-sql: true

  thymeleaf:
        enabled: true
        prefix: classpath:/templates/
        suffix: .html
        content-type: text/html
        encoding: UTF-8
        check-template-location: false
        check-template: false
        mode: HTML5
        cache: false

#logging:
 # pattern:
  #  console: "%d - %msg%n"
  #path: /Users/user12/documents/test
  #file: /Users/user12/documents/test/test1.log
  #level:
   #  com.nchu.controller.logTest: debug
  #level: debug

mybatis:
  config-location: classpath:mybatis-config.xml
 # type-aliases-package: com.nchu.domain.DO
  #mapper-locations: classpath:mybatis-mapper/*.xml


logging:
  level:
    org:
     hibernate: debug